export const userMock = 

{
  email: 'admin@admin.com',
  password: 'secret_admin'
}

export const token = 
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicGFzc3dvcmQiOiIkMmEkMDgkeGkuSHhrMWN6QU8wblpSLi5CMzkzdTEwYUVEMFJRMU4zUEFFWFE3SHh0TGpLUEVaQnUuUFciLCJpYXQiOjE2ODQ0NDI4MzQsImV4cCI6MTY4NDYxNTYzNH0.eHdD29jIeT0Ord5Q8dZBMi7qOuWNeAKemAqUnIAX6mM"

